# 4cc aet compiler Red 4.X.X - Advanced settings file

# Lines starting with # are comment lines and will be ignored by the compiler.
# 1 means enabled, 0 means disabled.

[Cache Clearing]
# If enabled, the "patches_contents" folder will be deleted after packing the
# cpks.
# If disabled, the exports you've compiled previously will be included in
# every cpk you pack, until you delete the "patches_contents" folder yourself.
# Default: 1
cache_clear = 1

[Allow Pausing]
# If enabled, the compiler will pause every time an error in the export is
# found, so you can stop it and fix the export right away then restart the
# compiler, without waiting for it to be finished compiling first.
# Also, the compiler will pause after it has finished.
# Even if disabled, the errors are written to the error.log file,
# so that you can check all the problems in one go after compiling is done,
# and fatal errors (i.e. missing vital stuff) will still pause the script.
# Disable it if you want to leave your pc running unattended without ever
# stopping.
# Default: 1
pause_allow = 1

[Strict File Type Check]
# If enabled, the compiler will reject model folders with disallowed file types.
# If disabled, the compiler will only give out info messages about them.
# Default: 1
strict_file_type_check = 1

[Pass-through]
# (This setting is usually only needed when making cup DLC.)
# If enabled, errors won't result in any of the exports' contents being skipped.
# Default: 0
pass_through = 0

[Admin Forcing]
# (This setting is only considered if Move Cpks mode is enabled.)
# If enabled, admin permissions will be requested even if the compiler does not
# think the PES folder is in a system folder.
# Use this if the compiler fails to move the cpks after compiling.
# Default: 0
admin_mode = 0

[Updates Checking]
# (This setting is only considered on Windows systems.)
# If enabled, the compiler will check if a newer version of the compiler
# exists on the github repository every time it is run. If a newer version
# exists, an update message will be displayed.
# After checking, the compiler won't check again for the following two hours.
# Default: 1
updates_check = 1
